name: Déploiement du Site Web

on:
  push:
    branches:
      - main  # Déclenche le workflow lors d'un push sur la branche 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code source
        uses: actions/checkout@v3

      - name: Debug Secrets
        run: |
          echo "🔍 Vérification des secrets GitHub..."
          if [ -z "${{ secrets.YOUR_API_KEY }}" ]; then
            echo "❌ ERREUR : Le secret YOUR_API_KEY n'est pas accessible !"
            exit 1
          else
            echo "✅ SUCCÈS : Le secret YOUR_API_KEY est accessible !"
          fi

      - name: Remplacer la clé API dans google-maps-loader.js
        run: |
          set -e  # Arrête l'exécution en cas d'erreur
          API_KEY=$(echo "${{ secrets.YOUR_API_KEY }}" | sed 's/[\/&]/\\&/g')
          sed -i "s/YOUR_API_KEY/${API_KEY}/g" google-maps-loader.js

      - name: Déployer le site web
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
